### ISSUE TITLE
Mine Contacts Fill is Incomplete

### ISSUE THREAD

**Issue by JMBennett** [missioncommand/old-mil-sym-java#10]
Creating a mine contact causes a white border around the right edge inside the shape.  This is most noticeable at smaller sizes.  This exists when trying to get 2525C and 2525B symbol sets.

This is using the .war render.

Query:
renderer/image/SUUPWMD---*****?size=10&symStd="2525C"

**Comment by michael-spinelli** [comment]
Can I get a screenshot of this?  I can't duplicate the issue using the URL you posted.

**Comment by michael-spinelli** [comment]
Fixed for bug 9 fixed this issue as well.  Fix present in release .48
