### ISSUE TITLE
dragon teeth GUMPOAOF

### ISSUE THREAD

**Issue by mg629** [missioncommand/old-mil-sym-java#101]
I receive dragon teeth (GUMPOAOF--****X) with only one center point. 
(-81.556,30.889)

I am assuming I need to have a bounding box for it which I create with a 1 meter radius.
([-81.557,31.888],[-81.555,30.89])

What should the control points be?  
If I make the control points the bounding box values.  The symbol shows up as a green line.
What should this symbol look like if I did it correctly?

**Comment by michael-spinelli** [comment]
I believe that's a single point graphic.  
You should be trying to get that as an image from the renderer:
https://github.com/missioncommand/mil-sym-java/wiki/Developer%27s-Guide#62-rendering-single-point-images
OR the following if you're using the web service:
https://github.com/missioncommand/mil-sym-java/wiki/Developer%27s-Guide#32single-coordinate-icon-based-symbology
![image](https://user-images.githubusercontent.com/5972575/80506200-42844400-8943-11ea-93a9-c0f505786713.png)

**Comment by mg629** [comment]
Thank you.
