### ISSUE TITLE
Correct way to handle G*M*OR----****X

### ISSUE THREAD

**Issue by mg629** [missioncommand/old-mil-sym-java#103]
It comes with a single point.

I tried to get the kml and it gave me a blue circle with question mark
http://{host}/mil-sym-service/renderer/kml/GFM*OR----****X?id=Box1&name=Box1&lon=-96.464&lat=30.671&Size=15

Is this correct or should I be putting a bounding box around this type of graphic?

**Comment by michael-spinelli** [comment]
The above is how you generate a KML placemark for a single point image.  Not what you'd want to do for a multipoint tactical graphic.  See below for getting KML for a multipoint symbol.

[https://github.com/missioncommand/mil-sym-java/wiki/Developer%27s-Guide#42multiple-coordinate-kml-based-symbology](https://github.com/missioncommand/mil-sym-java/wiki/Developer%27s-Guide#42multiple-coordinate-kml-based-symbology)

**Comment by mg629** [comment]
Thank you.  So this graphic should actually have multiple points normally?

If I create a bounding box around this single point (some radius), I can get a geoJson for this graphic also right?

**Comment by michael-spinelli** [comment]
oh, my mistake. I'm not seeing a G * M * OR----****X in the 2525C milstd.
When I did a search I found G * M * ORP which requires 3 points.  Are you using the correct symbol code?

The format parameter will let you get KML or GeoJSON back.

**Comment by mg629** [comment]
No you were right. This symbol needs 3 points.  My mistake.

G * M * OR -- -- ** ** X ROADBLOCKS, CRATERS, AND BLOWN BRIDGES

1. Anchor Points. This graphic requires three
anchor points. Points 1 and 2 define the
endpoints of the graphic, and point 3 defines the
location of one side of the graphic.
