### ISSUE TITLE
MILCO mines -  unable to set sonar classification confidence

### ISSUE THREAD

**Issue by JMBennett** [missioncommand/old-mil-sym-java#11]
This may be a function of my failure on 2525.  According to documentation I suspect to be able to use T1 in order to place the sonar classification confidence in the center of the object by appending it to my url.  I know this assumption is wrong due to section 5.5.2 where "T" is to be used before "T1", but I couldn't figure any other way. When trying that, the pound symbol is still shown and T1 appears to do nothing. 

Attempting to strip the pound symbol with icon=true results in a larger image than before with the pound symbol still displayed.

Query used:
renderer/image/SFUPWMGC--*****?T1=5&size=100&symStd=2525C

**Comment by michael-spinelli** [comment]
There is no T1 label for Warfighting graphics.  You can try setting AA if you want a label in the center:
renderer/image/SFUPWMGC--*****?AA=5&size=100&symStd=2525C
See pages 21-24 of 2525C. (or 27-30 in acrobat reader).  You'll still have the # symbol but the AA label will be next to it.

[Icon](https://github.com/missioncommand/mil-sym-java/wiki/Developer%27s-Guide#337----icon) just strips out modifier labels and no longer sizes symbols with respect to each other so they take the full space.  For example, a neutral symbol with size=35 is going to be smaller than a hostile symbol with size=35 (see page 32 (38) of 2525C for the table of symbol frame relative sizes).  If icon=true, the symbol will fill the 35x35 space while keeping the proper aspect ratio.

**Comment by michael-spinelli** [comment]
Added SCC modifier for sea mines of the MILCO variety.  set like:
renderer/image/SFUPWMGC--*****?SCC=5&size=100&symStd=2525C.
