### ISSUE TITLE
Fill color incorrect for some symbols

### ISSUE THREAD

**Issue by JMBennett** [missioncommand/old-mil-sym-java#13]
Using release v0.0.55.

The following icons show up with a fill color of white:

---

SPUP
SPSP

---

SASP
SAUP

---

SSUP
SSSP

---

SGUP
SGSP

---

SMUP
SMSP

---

Page fifteen of ms 2525c shows fill colors for all combinations of these base symbols.

Using the following URL to generate:
/mil-sym-service/renderer/image/SSUP-----------?symStd=2525C&size=100

**Comment by michael-spinelli** [comment]
fixed in .56 release
