### ISSUE TITLE
publish to maven central

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/old-mil-sym-java#14]
would it be possible to publish to maven central?

**Comment by michael-spinelli** [comment]
I would have to look into it.  We'd probably have to get that cleared like we did when we got permission to put the renderer on github.

**Comment by spyhunter99** [comment]
It's the same artifact and code. Just the binaries would be published using
maven. Just a suggestion. It would make things a bit easier (at least for
me ;) )

**Comment by jitpack-io** [comment]
Hi!
mil-sym-java is also available as a maven dependency from https://jitpack.io/#missioncommand/mil-sym-java/v0.0.68

**Comment by wallyatkins** [comment]
@michael-spinelli - you mentioned getting permission to put this code on GitHub. Could you elaborate on what that process was like? You can hit me up here (matthew dot w dot atkins dot ctr at mail dot mil) if preferred. Thanks!

**Comment by michael-spinelli** [comment]
I wasn't involved in the process myself but I'll send you an email and copy those that were involved.  Someone should be able to give you an idea.

**Comment by ruckc** [comment]
@michael-spinelli Any movement on publishing to maven central?  We are looking at trying to automate integration of this library in our tools and would like to avoid having to build the entire project from scratch to get to an easy level of automation.

**Comment by spyhunter99** [comment]
i can help facilitate

**Comment by michael-spinelli** [comment]
It's closer to happening now.  I finally got the thumbs up I needed.  EMP just got added to the mission command group and the plan is to put all the new projects, as well as the renderer, on maven central.  So hopefully in the coming weeks.

**Comment by michael-spinelli** [comment]
We will be posting the java and android ports to bintray:
https://bintray.com/missioncommand/maven/mil-sym-android#
https://bintray.com/missioncommand/maven/mil-sym-java#
