### ISSUE TITLE
what's the right code?

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/old-mil-sym-java#15]
referencing this image: https://upload.wikimedia.org/wikipedia/commons/3/31/1st_US_Armored_Division.png

I'm trying to recreate some of the icons using the renderer. Any idea what the right code is for 1st Stryker BDE?

**Comment by michael-spinelli** [comment]
The closest visual match I'm seeing is SUGPUCII--****\* which is Combat Infantry Fighting Vehicle but it's missing the three circles under the oval.  Can you give me a link to the wiki page the image is from?

**Comment by spyhunter99** [comment]
https://en.wikipedia.org/wiki/1st_Armored_Division_(United_States)

**Comment by wallyatkins** [comment]
From what I have seen the only way to get the three circles modifier on the icon is with MS2525D.

https://groups.google.com/forum/#!searchin/mission-command-milstd-renderer/stryker/mission-command-milstd-renderer/Gd_29sFmHK4/EaOPHsiUQcgJ

**Comment by michael-spinelli** [comment]
Yeah, while the symbology is modular, there's no way to call up those pieces to make a symbol on the fly in 2525C or previous.  That's the benefit of 2525D. 

Now I could make a way for you to put the pieces together with the renderer, but without an agreed upon symbol ID in the MilStd, it'd be useless to any other system but yours.

**Comment by spyhunter99** [comment]
good call, it was probably created with a D spec renderer. Thanks for looking into this!
