### ISSUE TITLE
Mine Contact Invalid Rendering

### ISSUE THREAD

**Issue by JMBennett** [missioncommand/old-mil-sym-java#16]
Using mil-sym-java release v0.0.73;

Several Decoy Moored and Decoy Bottom icons are not rendering properly in special case idents:

Exercise Pending Decoy Moored (SGUPWDMM--*****) shows up with a black hostile pentagon inside the icon, rendering the green icon not visible.

Exercise Assumed Friend Decoy Moored (SMUPWDMM--*****) contains a black box.

Suspect Decoy Moored (SSUPWDMM--*****) contains a black sub-surface icon.

Assumed Friend Decoy Moored (SAUPWDMM--*****) contains a black box.

Exercise Pending Decoy Bottom (SGUPWDMG--*****) contains a black hostile pentagon.

Assumed Friend Decoy Bottom (SAUPWDMG--*****) contains a black box.

Suspect Decoy Bottom (SSUPWDMG--*****) contains a black sub-surface icon.

Exercise Assumed Friend Decoy Bottom (SMUPWDMG--*****) contains a black box.

**Comment by michael-spinelli** [comment]
Fixed.  It will be in release .74 which should be available by Monday.
