### ISSUE TITLE
ICON=true does not function

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#17]
For the symbol code GHMPNEB-------- adding ?icon=true to the end of the path does not work.

For labels added manually to the path, it works, but for the "BIO" and "ENY" labels, it has no effect. I do not want the BIO/ENY labels showing up in my legend icon, so is there any other way to remove these labels?

![labelissue](https://cloud.githubusercontent.com/assets/7013389/13510971/de949ab2-e158-11e5-93af-9986bb690c4b.png)

**Comment by ChristinaKochan** [comment]
Same issue for GHMPNZ--------- and GHMPNEC--------

ENY is always there and for Chemical Release Event CML is always there.

**Comment by michael-spinelli** [comment]
Fixed.  I'll do a release sometime next week.

**Comment by ChristinaKochan** [comment]
This was helpful, so thank you. Is there any parameter I can include to get the icon only but with the Q directional arrow? Using "icon=true" gives me just the icon, even when I also use "Q=50", which I expect, but sometimes I would like to get the icon without labels but also with the graphic modifiers. Is this currently possible?

**Comment by michael-spinelli** [comment]
So, no "bio" label, but still having the direction of movement arrow?  The best I can give you right now is set ?KeepUnitRatio=false and only pass in the Q modifier.  But you'll still get the "BIO" label.  

Adding an option to turn off integral labels could potentially be done but would be low priority and not show up for a while.

**Comment by ChristinaKochan** [comment]
I guess my suggestion would be to have another parameter to keep graphic modifiers only and not text modifiers, but I don't know if anyone else would find this useful.

This isn't something that is high on our priority list either, so not having it available for a while would not be a huge deal. For our system, we retrieve the images for point symbols but then we draw the labels ourselves as separate graphics so we can turn them on and off to declutter our map. This way we don't have to re-render every symbol's image every time we turn labels on and off. The other reason we do this is so that the labels are not a part of the image so that when we select the symbol the colored selection outline appears around the image only and not around all of the labels as well. We still use the icon=true without any modifiers for our legend display.
