### ISSUE TITLE
Versioning, breaking changes, backwards compatability, new features

### ISSUE THREAD

**Issue by ruckc** [missioncommand/old-mil-sym-java#19]
Does mil-sym-java have a versioning standard (such as http://semver.org).  Is there any indictations by looking at version numbers for backwards compatability/breaking changes?  We are starting to incorporate this into a component and trying to see what level of testing do new releases need  and if there was an easy rubric we could follow depending on the version number changes.

**Comment by michael-spinelli** [comment]
For the most part we were just incrementing the patch number with every release.  But we also haven't introduced any breaking changes yet.  I did recently bring all ports to release number 0.1.1 just to indicate that they're at the same place.  With that, I'll be more closely following the standard you linked to from here out.  I don't expect any major version changes unless we get funded to do 2525D work.  But, my impression is that people are very hesitant to adopt that as it is a dramatic change from 2525B & 2525C.  Not really expecting many features either so may still just be patch updates for a long while.

**Comment by ruckc** [comment]
Ok, thanks.
