### ISSUE TITLE
Should set mime type from /renderer/image

### ISSUE THREAD

**Issue by ruckc** [missioncommand/old-mil-sym-java#2]
When testing this [example](http://mil-sym-renderer.missioncommand.cloudbees.net/renderer/image/OFPPC----------?size=48) the Response headers set the Content-Type to text/html.

**Comment by itaran** [comment]
Accidentally hit the close button, but reopened the issue.  Its been assigned.

**Comment by michael-spinelli** [comment]
The issue was an outdated war was uploaded.  
Corrected with current war which properly sets the mime type.

**Comment by michael-spinelli** [comment]
Join https://groups.google.com/forum/#!forum/mission-command-milstd-renderer
for renderer discussion.
