### ISSUE TITLE
Friendly graphics in black rather than blue

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#20]
I don't know that I would really consider this an issue, more of a request. My customer believes that friendly tactical graphic lines and areas should be shown in blue rather than black because of the following statement from the USAS for CS 13-14:

> 6.3.1 As all ABCS systems are capable of rendering symbols and graphics in color, then color shall be used and MIL-STD-2525B rules for color shall apply to all systems. Symbols denoting friendly affiliation shall be rendered by default in blue (Cyan icon, Crystal Blue fill, in accordance with 6.4.1). Hostile affiliations shall be rendered by default in red (in accordance with section 6.4.1).

In my opinion, this refers specifically to point symbols, not to tactical graphics. I am referring them to the following statement to explain why I believe they should be black, from 2525B ch. 2:

> 5.5.1.1 Affiliation. Affiliation refers to the threat posed by the battlespace object being represented. A tactical graphic may be black or off-white depending on display background, or affiliation may be indicated using color and/or text. If color is used, graphics denoting friend affiliation shall be shown in black, with other colors assigned in a manner consistent with the affiliation of the associated tactical symbols. By default, a graphic denoting hostile affiliation shall be shown in red. If red is not available, the graphic shall be drawn in black with the abbreviation “ENY” placed on the graphic in at least two places. In addition, if color is available, graphics indicating obstacles shall be drawn in green; otherwise, all obstacles shall be shown in black.

I would like to know why you have chosen to use black for friendly tactical graphics rather than blue. Mostly I just want support on why your way is correct so they will agree that in fact friendly tactical graphics should not be blue.

**Comment by michael-spinelli** [comment]
From Field Manual 1-02 Operational Terms and Graphics, Chapter 7, Graphic Control Measures:
COLORS
7-2.**When drawing manually or using a color computer-generated display,
show all friendly graphic control measures in black**. Show hostile graphic
control measures in red. If red is not available, place the abbreviation “ENY”
on the graphic in at least two places. If other colors are used to show friendly
or hostile factions, use a legend to ensure understanding of the use of colors
on the overlay. If neutral or unknown graphic control measures are included
on the overlay, use green and yellow if available. If green and yellow are not
available, draw neutral or unknown graphics in black and include the abbreviations
of “NEU” for neutral or “UNK” for unknown. Draw all obstacles—
friendly, hostile, neutral, unknown or factional—using green; if green is not
available, draw obstacles using black. (Obstacle graphics are shown in the
mobility and survivability section.)

You should be able to find the document with a google search.
