### ISSUE TITLE
Dummy Minefield (Dynamic) not rendering properly

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#21]
The Dummy Minefield (Dynamic) graphic is not rendering its internal circles. According to the documentation, "The internal of the graphic will be filled with “Unspecified Mines” (circles)."

Also, no matter what order I send the points to the service, the labels never seem to end up in the right place. The N labels should be at the left and right of the graphic, and the H labels should be at the top and bottom. The label placement also seems to change with the quadrant that the graphic is placed in.

**Comment by michael-spinelli** [comment]
So the problem with the Dummy Minefield (Dynamic) graphic is that when the mine type is set, it is sent as a separate graphic.  So when rendering, how do I know if the mine type is set or not?  If the MilStd or the USAS declared this was set by a modifier, I could do this easily.  Even if I just put in a way to support this, the problem is interoperability.  There's no way in the milstd or USAS of representing this connection.  So when the data is sent from one system to another, the connection would be lost and the graphic would look different on the receiving system.  Unless a change was made to the data schema to support this kind of relationship.

As for the label positioning, I'll ask the other Mike to take a look at that.

**Comment by michael-spinelli** [comment]
Just talked to one of our PASS/DDS guys.  If there's a way to establish that relationship, no one is using it.  But he's going confirm if that connection can even be made.  My impression was it couldn't.

**Comment by ChristinaKochan** [comment]
I agree with you, and it's exactly what I told my customer, but they are insistent that the circles be there. They think that they should be there as placeholders and then when the actual mines are there they will just cover the placeholders so you can't see them, basically pretending they aren't there. I wonder if it would be possible to just add a parameter to the modifiers list that is not transmitted that is only for rendering purposes. Most people may not use the parameter but for those of us that need the circles we can determine when we should set this param or not based on our own use cases.

**Comment by mdeutch3** [comment]
We tried to make the Hand ENY labels appear on opposing segments for simple areas with a limit of two each, assuming at least 4 segments but no special handling for irregular shaped areas. If we removed the labels limit of 2 each, and assuming that is allowed by Mil-Std-2525 , we could have alternating H and ENY labels along the entire graphic.

**Comment by michael-spinelli** [comment]
Well if you need something today, I'd say add Unspecified Mine Symbols (G_MPOMU---_***X) when you draw Dummy Minefield (Dynamic).  That would give you consistency when sending data to other systems too.  

I'm going to dig through the field manuals and see if there's something that can help our argument.  

I don't know if you'll eventually have to go through AIC (Army Interoperability Certification) testing but I know a system that got hit with a TIR for integrating the mines with the minefields.  The integrated mines didn't show up when they went across the wire to another system.  AIC said everything should be sent as individual symbols so the image stays the same on every system.  Although that system has made no change so far.

**Comment by michael-spinelli** [comment]
I checked with our PASS/DDS guy and there's no way to say this minefield has these mines and send it across the wire.  They're all sent separately.

**Comment by ChristinaKochan** [comment]
Yes, for now I think it will be reasonable to just add unspecified mines to the center of the graphic on our end. I think later we may add a combo box to our symbol editor to choose the type of mine to fill the graphic with and hopefully that will be sufficient for our customer until such time that there is a way to fill the graphic with placeholders and still maintain consistency across systems.

As far as the labels go, on further investigation it seems that the issue only really presents itself when the graphic is extraordinarily large because then even when you only have 4 control points you still can have 6-8 vertices drawn because of the skewing that happens due to the map projection. I attached a picture to illustrate this since I'm not sure I described it well. I think this is just a matter of training because realistically the user never needs a graphic this large. I would say the labels are fine as is unless you intend to add more support for irregular shaped areas.

![dummyminefielddynamic](https://cloud.githubusercontent.com/assets/7013389/15788555/ae93ed40-298d-11e6-8c5b-64ba607d6159.png)

**Comment by michael-spinelli** [comment]
Mike, I think we can do the alternating thing and take off the 2 labels each limit for irregular.  But maybe space them out a little more than you normally would for alternating labels if possible.

**Comment by mdeutch3** [comment]
A change was checked in for all renderer versions late Tuesday, 6-14.

**Comment by michael-spinelli** [comment]
fixed in release v0.1.5 for java and android, 0.1.7 for javascript
