### ISSUE TITLE
Aviation Lines should not display circles at anchor points

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#22]
Aviation Lines (Air Corridor, MRR, SAAFR, UAV Route, LLTR) should not display the circles at the anchor points. As shown in 2525B and USAS, the circles are separate graphics (ACPs or CCPs) and should not be displayed as part of these graphics. The templates for these graphics show what they should look like without the ACP/CCP graphics.

**Comment by michael-spinelli** [comment]
Mike, I know there's a reason we did it this way.  I just don't remember. I think it was another relationship issue where the graphics were sent separately.  The widths of each segment can be different, we wouldn't have the data necessary to size the ACP or CCP to match the size of the segments, so we always drew empty circles to make it look nice.  I'm not sure if there was more to it than that.  We may have been directed to do it this way by higher ups back in the day.  Like years ago before the renderer was a stand alone open source project and long before I had anything to do with it.

**Comment by mdeutch3** [comment]
Mil-Std-2525 and the USAS do not prohibit the use of end caps. ABSD decided to implement the end caps as the most effective way to join the segments when the one segment (2 points) limit was removed. The single point graphics can be positioned over the end caps.

**Comment by ChristinaKochan** [comment]
I suppose that's fair, albeit a little funny of a stance to take. If I went by everything the USAS does not explicitly prohibit I could basically do whatever I wanted with my graphics, right?

I also do realize the irony that my customer wants the placeholders for the Dummy Minefield (Issue #21) but doesn't want the placeholders for these line graphics. Who needs consistency?

If y'all have no intention of changing it then feel free to close this and we can manually remove the circles on our end. Thanks for quick response as usual.

**Comment by michael-spinelli** [comment]
We probably won't change this unless it comes through our chain of command.  Talking to some people that were here back in the day, we got a lot of complaints that the circles weren't there and people above us directed us to add them.

**Comment by ChristinaKochan** [comment]
Gotcha. I'll communicate this to my customer. Thanks!
