### ISSUE TITLE
Range Fan Labels

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#24]
The range fans (sector and circular) don't return the correct labels as shown in the USAS. According to the template, circular should show the AM range and altitude values for each ring, and sector should show the AM range, altitude, and both AN azimuths for each sector. I see that the documentation says "The “X” modifiers (“X”, “X1”, “X2”, “X3”) (Altitude) are not supported," but it doesn't say anything about AM or AN, so I would assume that means they should be supported, right?

Was it a conscious decision to not display these labels based on some documentation or is it just something that hasn't been implemented yet?

**Comment by mdeutch3** [comment]
The X labels (altitude) are supported for each range. Our direction was to omit the MIN RG and MAX RG labels. It is rendering the text as designed.

**Comment by ChristinaKochan** [comment]
Understood. Is there any plan to in the future support those additional labels?

**Comment by michael-spinelli** [comment]
I think that direction came before the renderer was broke out as its own thing and was part of another project.  We're going to look at adding them back in.

**Comment by mdeutch3** [comment]
Range labels have been added for circular and sector range fans. Azimuth labels have also been added for sector range fans. The changes have been checked in, I assume effective as of the next release.

**Comment by ChristinaKochan** [comment]
Great, thanks for the update!

**Comment by mdeutch3** [comment]
The default configuration displays the optional labels for each sector (range and azimuth). To turn off the optional labels add HIDEOPTIONALLABELS:true to the attributes.

**Comment by ChristinaKochan** [comment]
Good to know. Does this new attribute apply to just to the range fans at the moment?

**Comment by mdeutch3** [comment]
Yes. If you assign the attribute for other symbols it has no effect.

**Comment by ChristinaKochan** [comment]
Got it, thanks.

**Comment by michael-spinelli** [comment]
available in release v0.2.0

**Comment by mdeutch3** [comment]
I should have mentioned I was only speaking for multipoint sympbols. I don't know if this is used for units or single points.

**Comment by michael-spinelli** [comment]
fixed in release 0.1.10
