### ISSUE TITLE
Image metadata?

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#26]
We were previously running the image service inside of Jetty, but our customer is running the service locally directly from the jar files. When I do that, I now don't get any metadata for the png images. Do you know how I can fix this? I am using meta=true for all icon requests, but it just isn't having any effect when running locally without Jetty.

**Comment by ruckc** [comment]
Which metadata are you using from the endpoint?

**Comment by michael-spinelli** [comment]
I'll take a look

**Comment by ChristinaKochan** [comment]
We're using centerPoint and imageExtent to make sure our image is centered on the correct part of the control point.

**Comment by michael-spinelli** [comment]
fixed in release v0.1.12

**Comment by ChristinaKochan** [comment]
It would seem that with version 0.1.12 we are getting an Action Point for all tactical graphics and an empty generic Warfighting symbol for all others. I think it may be because of the switch from sanitizeSymbolID() to reconcileSymbolID() in SinglePointServer.java.

**Comment by michael-spinelli** [comment]
Sorry about that.  0.1.13 should be good.

**Comment by ChristinaKochan** [comment]
Well that's fixed, but I am seeing something else now. Metadata is not available when using icon=true. I attached the images I am retrieving as well as a screenshot of the browser to show my URL for each one.

![gusppx---------iconfalse](https://cloud.githubusercontent.com/assets/7013389/17758744/9db4c3ea-64b7-11e6-9886-f68bf14b09ba.png)
![gusppx---------iconfalsebrowser](https://cloud.githubusercontent.com/assets/7013389/17758742/9db2afc4-64b7-11e6-92e3-5ba02226762a.png)

![gusppx---------icontrue](https://cloud.githubusercontent.com/assets/7013389/17758743/9db3dd5e-64b7-11e6-85bc-5f51fa27bb0f.png)
![gusppx---------icontruebrowser](https://cloud.githubusercontent.com/assets/7013389/17758745/9db4e14a-64b7-11e6-8f3e-12a72980a1b4.png)

**Comment by michael-spinelli** [comment]
When icon=true, the assumption is that the symbol is going on a tree node, or preview window and not on a map.  Do you have a use case for needing the metadata when icon=true?

**Comment by ChristinaKochan** [comment]
Hmm, I will have to think about it. I thought there was some reason we were using icon=true with meta=true but I don't recall it now, so perhaps not. I'll get back to you shortly.
