### ISSUE TITLE
International Date Line

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#27]
I would like to know if there's a way to get a tactical graphic to cross the IDL rather than stretch across the rest of the world. For this example, I am sending "177.3,58.70 182.1,58.7" for my CONTROLPOINTS and "176.1,55.1,183.4,62.3" for my BBOX for symbol code GFGPALL-------- (Low Level Transit Route). I thought that simply sending the points not bound by +/- 180 would be sufficient, but I still get the stretched across graphic, so it would seem that the service is binding it to that extent for me.

![lltr](https://cloud.githubusercontent.com/assets/7013389/18183094/67e9635e-7058-11e6-8d1f-bb516aa558d2.png)

**Comment by mdeutch3** [comment]
Can you normalize the longitude values? e.g. 182.1=>182.1-360=-177.9.

**Comment by mdeutch3** [comment]
We've not run into this because clients tend to get their control points and bbox values from the viewers which have normalized coordinates.

**Comment by mdeutch3** [comment]
With the bbox and control points you stated the points do get normalized within the renderer using RenderSymbol2D. Here is the result in KML format:
<?xml version='1.0' encoding='UTF-8'?>
<kml xmlns='http://www.opengis.net/kml/2.2'>
<Document>
<Folder id="id"><name><![CDATA[name]]></name><visibility>1</visibility><Placemark><description><![CDATA[<b>name</b><br/>
desc]]></description><Style id="lineColor"><PolyStyle><color>440000ff</color><colorMode>normal</colorMode><fill>1</fill><outline>0</outline></PolyStyle></Style><MultiGeometry><Polygon><outerBoundaryIs><LinearRing><altitudeMode>clampToGround</altitudeMode><tessellate>1</tessellate><coordinates>-182.7,58.78674699 -177.89999991,58.78674699 -177.89999991,58.61325301 -182.7,58.61325301 -182.7,58.78674699</coordinates></LinearRing></outerBoundaryIs></Polygon></MultiGeometry></Placemark><Placemark><description><![CDATA[<b>name</b><br/>
desc]]></description><Style id="lineColor"><LineStyle><color>ff000000</color><colorMode>normal</colorMode><width>3</width></LineStyle></Style><MultiGeometry><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>177.3,58.78674699 -177.89999991,58.78674699</coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>177.3,58.61325301 -177.89999991,58.61325301</coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>177.35398521,58.7 177.35241652,58.6792401 177.34780151,58.65968679 177.34040854,58.64247606 177.33066707,58.62860857 177.31914337,58.61889001 177.30650716,58.61388542 177.29349284,58.61388542 177.28085662,58.61889001 177.26933292,58.62860857 177.25959145,58.64247606 177.25219849,58.65968679 177.24758348,58.6792401 177.24601479,58.7 177.24758348,58.7207599 177.25219849,58.74031321 177.25959145,58.75752394 177.26933292,58.77139143 177.28085662,58.78110999 177.29349284,58.78611458 177.30650716,58.78611458 177.31914337,58.78110999 177.33066707,58.77139143 177.34040854,58.75752394 177.34780151,58.74031321 177.35398521,58.7</coordinates></LineString><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-177.84601471,58.7 -177.84758349,58.6792401 -177.85219831,58.65968679 -177.85959155,58.64247606 -177.86933302,58.62860857 -177.88085672,58.61889001 -177.89349266,58.61388542 -177.90650717,58.61388542 -177.91914347,58.61889001 -177.93066717,58.62860857 -177.94040864,58.64247606 -177.94780152,58.65968679 -177.95241634,58.6792401 -177.95398512,58.7 -177.95241634,58.7207599 -177.94780152,58.74031321 -177.94040864,58.75752394 -177.93066717,58.77139143 -177.91914347,58.78110999 -177.90650717,58.78611458 -177.89349266,58.78611458 -177.88085672,58.78110999 -177.86933302,58.77139143 -177.85959155,58.75752394 -177.85219831,58.74031321 -177.84601471,58.7</coordinates></LineString></MultiGeometry></Placemark><Placemark><name><![CDATA[LLTR NAME]]></name><Style><IconStyle><scale>.7</scale><heading>0</heading><Icon><href></href></Icon></IconStyle><LabelStyle><color>FFFFFFFF</color><scale>0.8</scale></LabelStyle></Style><Point><extrude>1</extrude><altitudeMode>relativeToGround</altitudeMode><coordinates>179.69901397,58.72712036</coordinates></Point></Placemark><Placemark><name><![CDATA[Max Alt: 13123.4 ft. MSL]]></name><Style><IconStyle><scale>.7</scale><heading>0</heading><Icon><href></href></Icon></IconStyle><LabelStyle><color>FFFFFFFF</color><scale>0.8</scale></LabelStyle></Style><Point><extrude>1</extrude><altitudeMode>relativeToGround</altitudeMode><coordinates>179.6976271,59.15119471</coordinates></Point></Placemark><Placemark><name><![CDATA[Min Alt: 9842.5 ft. MSL]]></name><Style><IconStyle><scale>.7</scale><heading>0</heading><Icon><href></href></Icon></IconStyle><LabelStyle><color>FFFFFFFF</color><scale>0.8</scale></LabelStyle></Style><Point><extrude>1</extrude><altitudeMode>relativeToGround</altitudeMode><coordinates>179.69728038,59.24757864</coordinates></Point></Placemark><Placemark><name><![CDATA[Width: 40000.0]]></name><Style><IconStyle><scale>.7</scale><heading>0</heading><Icon><href></href></Icon></IconStyle><LabelStyle><color>FFFFFFFF</color><scale>0.8</scale></LabelStyle></Style><Point><extrude>1</extrude><altitudeMode>relativeToGround</altitudeMode><coordinates>179.69693367,59.34396257</coordinates></Point></Placemark><Placemark><name><![CDATA[Name: NAME]]></name><Style><IconStyle><scale>.7</scale><heading>0</heading><Icon><href></href></Icon></IconStyle><LabelStyle><color>FFFFFFFF</color><scale>0.8</scale></LabelStyle></Style><Point><extrude>1</extrude><altitudeMode>relativeToGround</altitudeMode><coordinates>179.69658695,59.44034651</coordinates></Point></Placemark><Placemark><name><![CDATA[DTG Start: ]]></name><Style><IconStyle><scale>.7</scale><heading>0</heading><Icon><href></href></Icon></IconStyle><LabelStyle><color>FFFFFFFF</color><scale>0.8</scale></LabelStyle></Style><Point><extrude>1</extrude><altitudeMode>relativeToGround</altitudeMode><coordinates>179.69797382,59.05481078</coordinates></Point></Placemark><Placemark><name><![CDATA[DTG End: W]]></name><Style><IconStyle><scale>.7</scale><heading>0</heading><Icon><href></href></Icon></IconStyle><LabelStyle><color>FFFFFFFF</color><scale>0.8</scale></LabelStyle></Style><Point><extrude>1</extrude><altitudeMode>relativeToGround</altitudeMode><coordinates>179.69832053,58.95842685</coordinates></Point></Placemark></Folder>
</Document>
</kml>

**Comment by mdeutch3** [comment]
Here is the MKL displayed in Google Earth
![lltr](https://cloud.githubusercontent.com/assets/5973557/18184847/cfcfe4ec-7068-11e6-881b-a5f4787f15eb.png)

**Comment by ChristinaKochan** [comment]
Hmm, those are the coordinates I am getting as well. And normalizing has no effect on the returned points or how it appears on the map. So it must be our map that is doing the stretching. We're using ArcGIS Runtime for .NET.

Next time I see something like this I'll check with the KML on Google Earth as well and if it's drawing correctly there I'll know it's our map rendering it wrong. Thanks for the prompt help, as usual!

**Comment by ruckc** [comment]
@ChristinaElaine ask the map api vendor your using most support it but it may be a weird hack.

**Comment by mdeutch3** [comment]
For whatever it's worth it varies with different application. In my JavaScript 2D testers, using Google Maps I see no problems crossing the IDL from either side. With Leaflet it exhibits the same problem you're seeing. With OL3 it displays the symbol spanning the IDL but then throws a stray line across the entire map.

**Comment by michael-spinelli** [comment]
Christina, were you able to come up with a solution for your ArcGIS based map?
