### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by jtharp** [missioncommand/old-mil-sym-java#30]
I am looking for the ability to change the icon (internal symbol / within the frame) color by passing in a parameter to the http get request.

Right now we use line color and fill color to signify special symbols in our system but right now I don't see a method of changing the icon color.

**Comment by michael-spinelli** [comment]
Use ICONCOLOR
http://127.0.0.1:6789/mil-sym-service/image/SFPPS----------?SIZE=90&ICONCOLOR=0000FF

**Comment by jtharp** [comment]
Thanks, did not see it mentioned in the developer guide.
Is it ICONCOLOR=0000FF or ICONCOLOR=0x0000FF

**Comment by michael-spinelli** [comment]
You're right, I'll update.

Either should work.
