### ISSUE TITLE
Circular Range Fan labels are incorrect

### ISSUE THREAD

**Issue by y2kbowen** [missioncommand/old-mil-sym-java#31]
A circular range fan is defined to have labels MIN RG for AM MAX RG (1) for AM1 and MAX RG (2) for AM2. For example:
if AM  set to 50000 then is should be displayed and MIN RG 50000
if AM1 set to 150000 then is should be displayed as MAX RG (1) 150000
if AM2 set to 250000 then it should be displayed as MAX RG (2) 250000

What is rendered is  RG 50000
                                 RG1 150000
                                 RG2 250000

Picture of what is shown is attached. Also a fiddler capture of the call is attached.
 
![circularlabelerror](https://cloud.githubusercontent.com/assets/4991352/20985941/3209fb60-bc8c-11e6-937d-111fa29cdb5f.jpg)
![circularlabelerrorfiddlercapture](https://cloud.githubusercontent.com/assets/4991352/20985942/320a5754-bc8c-11e6-830b-1d7ead06d249.jpg)

**Comment by mdeutch3** [comment]
Did you set the altitudeDepth (X) array? I don't see it in the modifiers.

**Comment by michael-spinelli** [comment]
He's not talking about altitude.  He's saying our labels for AM are wrong.

**Comment by mdeutch3** [comment]
Our design intent was to keep the text to a minimum for range fan ranges and they followed the example that was shown for sector range fans, only using RG for the labels. Also if the HIDEOPTIONALLABELS modifier is set then it omits the ranges.

**Comment by michael-spinelli** [comment]
If sector uses RG, and that's what the milstd says, that's fine.  But we should probably fix Circular Range Fan.

**Comment by mdeutch3** [comment]
The range labels have been modified, the change has been checked in.

**Comment by michael-spinelli** [comment]
A new release will come out next week.

**Comment by michael-spinelli** [comment]
fixed in release v0.1.16

**Comment by y2kbowen** [comment]
The update labels are not correct in build v0.1.16. Picture attached.

if AM set to 100000 then is should be displayed and MIN RG 100000 (This is rendering correctly)
if AM1 set to 400000 then is should be displayed as MAX RG (1) 400000 (This is showing MIN RG (1))
if AM2 set to 800000 then it should be displayed as MAX RG (2) 800000 (this is showing MIN RG (2)) 

![circular range fan bad labels](https://cloud.githubusercontent.com/assets/4991352/21657050/32f16cf6-d286-11e6-8946-3236c5a76203.png)

**Comment by mdeutch3** [comment]
The labels have been changed to display MAX RG.

**Comment by michael-spinelli** [comment]
fixed in release 0.1.17
