### ISSUE TITLE
USAS 2525B update removed center of sector arrow from circular range fan

### ISSUE THREAD

**Issue by y2kbowen** [missioncommand/old-mil-sym-java#32]
I am not sure if this is a problem for the version of the spec your project supports.  As shown below you are correctly rendering the circular range fan according to the spec provided in MIL-STD-2525B w/change 2 dated 3/7/2007.  However, the update provided by USAS for COEV1 dated May 7 2014 shows the arrow has been removed.   

![2525bchg2rangefanspec](https://cloud.githubusercontent.com/assets/4991352/21026839/0126276c-bd54-11e6-81bd-3400a84bfb52.png)
![usascircularrangefan](https://cloud.githubusercontent.com/assets/4991352/21026892/399db0c4-bd54-11e6-8d80-63f9601c73c1.png)

**Comment by mdeutch3** [comment]
If you supply just the center point to the renderer it will display without the arrow.

**Comment by y2kbowen** [comment]
Cool, thanks.

**Comment by y2kbowen** [comment]
Providing only the center point to the renderer displays the image without the arrow.  Is it correct for the image to have the arrow?  

![circularrangeimage](https://cloud.githubusercontent.com/assets/4991352/21235639/3787eb88-c2bd-11e6-8682-810ca6c17e9d.png)

**Comment by mdeutch3** [comment]
For Rev B you can have the direction indicator (arrow) if you use multiple points. pt0 is the center point, pt1 defines the end point of the arrow, and subsequent points define the concentric radii.
