### ISSUE TITLE
Installation Symbols for EMS

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#33]
The _isInstallation_ method of the SymbolsUtilities is used to determine if a symbol is an installation symbol.  This works for War Fighting Symbols, but it does not for EMS Symbols that are installations according to the MIL-STD-2525C.   For example, the following are a few EMS symbols that are installations (according to the H in the symbol code).

E*O*AC----H****  (EMERGENCY MEDICAL OPERATION INSTALLATION)
E*O*AD----H****  (EMT STATION LOCATION)
E*O*AG----H****  (HEALTH DEPARTMENT FACILITY)

Should the _isInstallation_ method be updated to return true for these types of symbols?

**Comment by michael-spinelli** [comment]
I'll revisit it.

**Comment by michael-spinelli** [comment]
Updated to include EMS installations.
Fixed in release v0.1.16
