### ISSUE TITLE
Some METOC Symbols Rendering Incorrectly

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#35]
The following METOC symbols are not rendering correctly according to the standard:

•	|METOC|OCEANIC|HYDROGRAPHY|DEPTH|DEPTH AREA
The standard shows an area with three different colors; blue, pale blue, and white

•	|METOC|OCEANIC|HYDROGRAPHY|PORTS AND HARBORS|PORTS|ANCHORAGE (LINE)
There is no anchor symbol in the KML returned.

•	|METOC|OCEANIC|HYDROGRAPHY|PORTS AND HARBORS|PORTS|ANCHORAGE (AREA)
There is no anchor symbol in the KML returned.

**Comment by mdeutch3** [comment]
Can you provide the function you are using and the parameter data for Depth Area?
For the Anchorage line and area, the anchorage symbol you are referring to is a separate single point graphic that you would render: WOS-HPBA--P----

**Comment by david-melendez** [comment]
I have been looking at the DEPTH AREA and I have come to the conclusion that I am incorrectly rendering the KML that the renderer is sending me. 

 

Thank you for your assistance.

 

 

David Melendez

 <mailto:david.melendez@nova-tech-solutions.com> david.melendez@nova-tech-solutions.com

Software Engineer

Nova Tech Solutions
