### ISSUE TITLE
How to generate the Pentagons of the Limited Access Area Graphic

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#37]
According to the MILSTD 2525C,  the Limited access area is comprised of a general graphic area and a one or more pentagons shapes.   I can generate the general area easily enough, but how are the pentagons generated?  Are they separate symbols/graphics that must be generated?

**Comment by mdeutch3** [comment]
Yes, those are separate symbols. According to Mil-Std-2525:
Note: Although unit symbols are not part of tactical
graphic area, numerous unit symbols can be included in
the area for presentation.

**Comment by david-melendez** [comment]
Thanks for the clarification.
