### ISSUE TITLE
Version 0.1.17 introduced a problem into multi point server

### ISSUE THREAD

**Issue by y2kbowen** [missioncommand/old-mil-sym-java#41]
Version 0.1.17  is returning 0 bytes on some graphics like Circular Sensor ranges and Rectangular Targets. I attached a fiddler trace. Build 0.1.16 does not have the problem. The result code in 17 is 504. No exceptions are shown from the service.

Version17:
![version17](https://cloud.githubusercontent.com/assets/4991352/22079088/373bfae2-dd80-11e6-8c8a-03d7fb54d6f2.png)

Version 16:
![version16](https://cloud.githubusercontent.com/assets/4991352/22079111/48abd2b6-dd80-11e6-8019-53dfd36624b6.png)

**Comment by michael-spinelli** [comment]
Fixed in v0.1.18
