### ISSUE TITLE
Corridor Graphics Not Rendering Text for MIL-STD-2525B

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#42]
When rendering corridor graphics with the standard set to the _MIL-STD-2525B_ standard, the rendered KML does not contain the text that I see in the same graphics when using the _MIL-STD-2525C_ standard.  The following is a code fragment taken from some test code.  Note the the **_r_** variable is a reference to the renderer and the SaveKmlToFile()_ is a method used to save the generated KML.

```
// With no min max (B Standard)
kml = r.RenderMultiPointSymbol(
            "ID",
            "AIR CORRIDOR",
            "AIR CORRIDOR",
            "GFGPALC---****X",
            "-86.6125335693359,30.673957824707 -86.5828399658203,30.674295425415",
            "clampToGround",
            50000,
            "",
            "{\"modifiers\":{\"AM\":[449]}}",
            0,
            0); // <- This indicates the B standard
        
SaveKmlToFile(kml, "C:\\testdata\\StdB_AirCorridor_WithNoMinMax.kml");
               
// With no min max (C Standard)
r.RenderMultiPointSymbol(
            "ID",
            "AIR CORRIDOR",
            "AIR CORRIDOR",
            "GFGPALC---****X",
            "-86.6125335693359,30.673957824707 -86.5828399658203,30.674295425415",
            "clampToGround",
            50000,
            "",
            "{\"modifiers\":{\"AM\":[449]}}",
            0,
            1); // <- This indicates C standard
        
SaveKmlToFile(kml, "C:\\testdata\\StdC_AirCorridor_WithNoMinMax.kml"); 
```

I have attached the generated files to this issue.   You will see that the kml rendered using the C standard generates text for width, min/max altitude, etc.   Should the Air Corridor graphics render the same for both standards (with the exception of the middle line for the corridor specified in the B standard)?

[StdB_AirCorridor_WithNoMinMax.txt](https://github.com/missioncommand/mil-sym-java/files/717920/StdB_AirCorridor_WithNoMinMax.txt)
[StdC_AirCorridor_WithNoMinMax.txt](https://github.com/missioncommand/mil-sym-java/files/717921/StdC_AirCorridor_WithNoMinMax.txt)

**Comment by mdeutch3** [comment]
Air Corridor renders differently for Rev C than for Rev B. Rev B does not have the modifiers above the line as does Rev C.

**Comment by david-melendez** [comment]
The B standard alone does not have the same modifiers, but the USAS document (Unified Specification for ABCS Symbology (USAS) for the Fires COP Quarterly Release to BC Marshall / Capability Set 11-12) does add these modifiers to the Air Corridor graphic.   The Java renderer appears to support these modifiers for the graphic, it just does not actually render text for these modifiers.

My question is does the additions in the USAS document for supporting these modifiers extend to actually rendering this information in the KML?  Does supporting these modifiers require the renderer to generate KML for these modifiers?

 

The USAS has the following information for the Air Corridor graphic:

 Pub – Sub Requirements:
This is a multipoint line with a minimum of two points (one segment): Each point: Symbol > Symbol_Points > Point. Each vertex can be overlaid by an optional ACP or CCP, sent as a separate tactical graphic.

Name: T: Symbol > Operational_Attributes > Unique_Designator1
Segment Name: T1: Symbol > Operational_Attributes > Unique_Designator2 (optional)
Min Alt: H: Symbol > Operational_Attributes > Additional_Info1
Max Alt: H1: Symbol > Operational_Attributes > Additional_Info2
Width: H2: Symbol > Operational_Attributes > Additional_Info3
Time start: W: Symbol > Operational_Attributes > DTG_1
Time end: W1: Symbol > Operational_Attributes

**Comment by michael-spinelli** [comment]
H, H1, H2 are used to shape the symbol.  So they're still important values.  They're just not listed in a block above the symbol like in 2525C.

**Comment by david-melendez** [comment]
Thanks for the clarification.
