### ISSUE TITLE
Fire Support Area, Irregular label

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#43]
My customer is requesting that the T label of the Irregular FSA area be next to the "FSA" rather than beneath it.

![tbelow](https://cloud.githubusercontent.com/assets/7013389/22443454/8952d2c8-e704-11e6-9382-61d26c5071a3.png)
![tbeside](https://cloud.githubusercontent.com/assets/7013389/22443453/89500958-e704-11e6-913d-934a49d552d0.png)

**Comment by mdeutch3** [comment]
The T modifier has been moved so that it is next to the FSA label.

**Comment by ChristinaKochan** [comment]
Thanks!

**Comment by michael-spinelli** [comment]
fixed in release v0.1.19
