### ISSUE TITLE
FAADEZ icon for 2525B

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#45]
When using the symbol code for FAADEZ (GHGPAAF--------) I'm getting the icon for the 2525C version of the symbol code, which is SHORADEZ, rather than 2525B. The JSON features for the actual multipoint symbol has the correct FAADEZ label.

![ghgpaaf---](https://cloud.githubusercontent.com/assets/7013389/22527792/14f2f82a-e896-11e6-90ec-e8a7eccc2a30.png)
![faadez](https://cloud.githubusercontent.com/assets/7013389/22527791/14f2af5a-e896-11e6-99ac-5b4e53fcf919.png)

**Comment by michael-spinelli** [comment]
fixed in release v0.1.19
