### ISSUE TITLE
Unknown Release Events icons aren't displaying correctly

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#49]
The icons for the following symbols are not displaying correctly:
- Release Events, Biological
- Release Events, Chemical
- Nuclear Detonations Ground Zero

The text inside the yellow symbol is also yellow, so the B, C, and N aren't visible for Unknown symbols.

![ghmpneb--------](https://cloud.githubusercontent.com/assets/7013389/22947434/8dc74326-f2c0-11e6-902c-be97e6834614.png)
![gumpneb--------](https://cloud.githubusercontent.com/assets/7013389/22947435/8dc991f8-f2c0-11e6-83a2-d4300599ea42.png)

**Comment by michael-spinelli** [comment]
Altered outline technique.  Will be fixed in next release v0.1.23
