### ISSUE TITLE
Duplicate labels

### ISSUE THREAD

**Issue by murphylemur** [missioncommand/old-mil-sym-java#5]
Some graphics such as Restrictive Fire Area (RFA) Circular returns the same exact label 4 times.  This is the url I was using:

_renderer/mp3d/G_F_ACRC--_**_X?symbolCode=G_F*ACRC--***_X&controlPoints=-99.1979973201177,32.8801920355805&pixelWidth=0&pixelHeight=0&FORMAT=1&SYMSTD=1&scale=1&modifiers={"modifiers":{"AM":[5000]}}_

**Comment by michael-spinelli** [comment]
Fixed.  Code checked in.  Will be in the 0.0.41 release.  

Also, don't use a scale of 1.
[SCALE](https://github.com/missioncommand/mil-sym-java/wiki/Developer%27s-Guide#436----scale-for-3d)
