### ISSUE TITLE
Sector Range Fan center line

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#53]
I may be mistaken, but I believe the center line of the Sector Range Fan should always be pointing due north. I have found that the line instead points toward the center of the outermost sector. Is this correct?

![image](https://cloud.githubusercontent.com/assets/7013389/23226364/e5e3aa1e-f8fa-11e6-82f3-84fe00b7799b.png)

**Comment by mdeutch3** [comment]
Our direction was to use the azimuth of the center of the maximum range sector for the orientation indicator.

**Comment by michael-spinelli** [comment]
The template for this symbol also says "Center of Sector" in reference to the arrow.

**Comment by ChristinaKochan** [comment]
I will relay this information to my customer. Thank you!
