### ISSUE TITLE
Special C2 Headquarters

### ISSUE THREAD

**Issue by ChristinaKochan** [missioncommand/old-mil-sym-java#54]
I believe the Special C2 Headquarters Component should always have the headquarters staff present. It does not seem to return with the staff unless you add the HQ modifier code.

SUGPUH----A----
![sugpuh----a----](https://cloud.githubusercontent.com/assets/7013389/23273868/5315f1de-f9c6-11e6-992b-fcbe4dabc907.png)
SUGPUH---------
![sugpuh---------](https://cloud.githubusercontent.com/assets/7013389/23273869/5316c01e-f9c6-11e6-8978-1b3fa8ee21c8.png)

**Comment by michael-spinelli** [comment]
fixed in next release, v0.1.23
