### ISSUE TITLE
Generating Rotated Symbol

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#55]
There are certain single point symbols that can be rotated by 90, 180, or 270 degrees (e.g. Brief Contact).  How does one specify the rotation value to send to the renderer?  Is this possible?

**Comment by michael-spinelli** [comment]
Right now you can only do it if you're using the jars directly rather than using the web service.  I'm debating if I should Add Rotation to MilStdAttributes or just use ModifiersTG.AN_Azimuth.  The MilStd and USAS don't really get into how the rotation value is stored.  Do you have any insight into the use case for rotating these symbols?

**Comment by david-melendez** [comment]
We are saving the symbols and graphics we are drawing on a map into a file.  If a user has specified a rotation, I want to save that rotation value so that if the file is sent to another user, the graphic is displayed as rotated.

Also, I am caching the symbols that I have renderer to that I do not have to call the renderer every time I need to draw a symbol.   Currently, I retrieved the cached bitmap, check to see if I need to rotate it, perform the rotation, and then draw the bitmap.  If the renderer sent me a rotated graphic, I could cache that symbol and draw as needed.

The real use case is drawing thousands of symbols that are being updated every couple of seconds and my drawing method has to check to see if each of these symbols has a rotation value associated with it and if apply the rotation if necessary.  We are talking milliseconds for this operation, but every millisecond counts.

**Comment by michael-spinelli** [comment]
Are you using the web service or the jars directly?

**Comment by david-melendez** [comment]
I am currently using the web service.

**Comment by david-melendez** [comment]
I think I will be able to rework my code to use the jars directly.  That way I can set the rotation to the value I need.

**Comment by david-melendez** [comment]
I have converted my code to use the jars directly, so this is no longer an issue for me.
