### ISSUE TITLE
How to create KML or JSON of single point graphics/symbols such as Destroy

### ISSUE THREAD

**Issue by murphylemur** [missioncommand/old-mil-sym-java#6]
Is it possible to create KML or JSON representation of a point graphic such as Destroy/Neutralize/Interdict?   I can create it as an icon but I'm not interested in that graphic as an icon.  Here is an example of a call I've been trying to get the Destroy graphic:

_renderer/mp3d/G_T_D-----_**_X?symbolCode=G_T*D-----***_X&controlPoints=-93.8646979368204,42.351531037291&FORMAT=0&SYMSTD=1&scale=300.00&modifiers={'modifiers':{'T':}}_

**Comment by michael-spinelli** [comment]
Currently, your only other option for single point graphics is SVG.  Although the SVG doesn't actually have any path data.  It's just an SVG with an image embedded as a dataurl.

[https://groups.google.com/forum/#!topic/mission-command-milstd-renderer/Mw0yW0UpQh0](https://groups.google.com/forum/#!topic/mission-command-milstd-renderer/Mw0yW0UpQh0)

**Comment by murphylemur** [comment]
Thank you, that will have to do for now.

**Comment by michael-spinelli** [comment]
Closing issue for now
