### ISSUE TITLE
How to specify points for Tropical Storm Wind Areas and Date/Time Labels Graphic

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#65]
I am trying to determine how to specify the points necessary to draw 'Tropical Storm Wind Areas and Date/Time Labels' graphic (WA-DWSTSWA--A--).  This graphic appears to have multiple circles as well as a line from the Date/Time label to the storm.   It appears that the graphic can have three different area specifications for different wind speeds.

Basically, can you tell me what is necessary to draw an image as shown in the MIL-STD-2525C?

**Comment by mdeutch3** [comment]
This issue is being worked.

**Comment by michael-spinelli** [comment]
Still trying to get some direction on how this symbol should be rendered.

**Comment by michael-spinelli** [comment]
Going to ask again at work.  No one seems to want to get back to me on this graphic.

**Comment by david-melendez** [comment]
Thanks for the update.

 

 

David Melendez

 <mailto:david.melendez@nova-tech-solutions.com> david.melendez@nova-tech-solutions.com

Software Engineer

Nova Tech Solutions

**Comment by michael-spinelli** [comment]
My question is moving along and more people are looking at it but I don't have an answer for you yet.

**Comment by david-melendez** [comment]
Thanks for the update.

 

 

David Melendez

 <mailto:david.melendez@nova-tech-solutions.com> david.melendez@nova-tech-solutions.com

Software Engineer

Nova Tech Solutions

**Comment by michael-spinelli** [comment]
Navy holds the key but I was never able to get a response.
