### ISSUE TITLE
Task force modifier rendered as a seperate box when an echelon is added

### ISSUE THREAD

**Issue by jcteague** [missioncommand/old-mil-sym-java#7]
when a task force unit is rendered with a echelon, there is a space between the task force box and the unit.

![sfgpuci---ef---](https://cloud.githubusercontent.com/assets/75046/5115005/3285c326-7003-11e4-920e-6b97bdc99e9f.png)

This only happens when a echelon is provided

**Comment by michael-spinelli** [comment]
Tweaked task force indicator rendering when echelon present.
Code checked in. Fix will be in release .41
