### ISSUE TITLE
Rendered KML Does Not Contain Necessary Text for Small Areas

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#70]
The tool I am developing allows the user to click on a map to draw multi-point area graphics.   For some graphics, if the area drawn is too small, the KML rendered for a modifier value does not return all the information.

For example, the Restricted Operations Zone will not have data in the KML for all the fields:

- Min Altitude
- Max Altitude
- Time From:
- Time To:

My tool converts the data return to ellipses.  Below are three images: a ROZ with a small area defined, a ROZ with a medium area defined, and a ROZ with a large area defined.

Is there a way to force the renderer to generate all the required text no matter the size specified by the points?  My customer needs the ability to see all the text no matter what the defined size.

**Comment by mdeutch3** [comment]
RendererSettings setAutoCollpaseModifiers. The default setting is true so you would set it to false.

**Comment by david-melendez** [comment]
Thank you! That's what I needed.
