### ISSUE TITLE
Symbol Icon Colors Incorrect

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#72]
There are certain symbols that when you generate an icon for the symbol/graphic, the color in the icon image does not match the specification.

**FORESHORE** 
- WO-DHCF----L---
- WO-DHCF-----A--

For both of these graphics, the standard says that the color is Yellow-Green.  When the actual graphic is rendered, the color is correct.  However, the icon generated is Green (not Yellow-Green).

![foreshorecolor](https://cloud.githubusercontent.com/assets/22623059/26364391/cf2c613a-3fa9-11e7-9b05-b69706885f17.PNG)

**UNDERWATER DANGER/HAZARD**
- WO-DHHD-----A--

This graphic should be blue filled with dotted black line.  Again, the graphic is correct but the icon is not.  The icon appears to be using CYAN for the color.

![underwaterdangercolor](https://cloud.githubusercontent.com/assets/22623059/26364467/07b30950-3faa-11e7-980a-be8d94cb7dc5.PNG)

**DISCOLORED WATER**
- WO-DHHDD----A--

Discolored water has the same problem as Underwater Danger/Hazard graphic.

![discoloredwatercolor](https://cloud.githubusercontent.com/assets/22623059/26364586/70f792dc-3faa-11e7-8b37-6a455eda842c.PNG)

**OFFSHORE LOADING FACILITY (Line)**
- WO-DHPMO---L---

The standard says that this line should be grey solid line (and renders correctly).  The icon generated, however, shows a grey line outlined by black edges.

![offshoreloadingfaccolor](https://cloud.githubusercontent.com/assets/22623059/26364771/0dac497e-3fab-11e7-8818-7fc35f947cca.PNG)

**DEPTH AREA**
- WO-DHDDA----A--

The Depth Area symbol/graphic should be a combination of colors, (blue, pale blue, white) and renders correctly.  However, the icon generated shows only a black symbol.

![depthareacolor](https://cloud.githubusercontent.com/assets/22623059/26364904/92c1b23e-3fab-11e7-8230-5be7ee261617.PNG)

**Comment by michael-spinelli** [comment]
Fixed, you'll see it in the next release.  Except for depth area.  That's a little more involved because of the multiple colors but it is blue now instead of black.

**Comment by michael-spinelli** [comment]
v0.1.27
