### ISSUE TITLE
FSCL and RFL Line Graphics Don't Always Show All Text

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#73]
When drawing a Fire Support Coordination Line (FSCL) or a Restrictive Fire Line (RFL), if the graphic only has two points and the points are close together, the renderer will not generated the endcap text for end point.  If the points are further apart, both endcap tests are rendered.  The below pictures shows four graphics.  You will see that two of the graphics are shorter and don't contain the expected FSCL or RFL.

![fscl_and_rfl](https://user-images.githubusercontent.com/22623059/27135260-b0ec060e-50dd-11e7-90b4-01a148a136fa.PNG)

I assume that this is by design.  My question is whether there is a way to make the renderer generate both endcap texts no matter the size of the line?

**Comment by michael-spinelli** [comment]
Can you give me the renderer input for the lines that didn't show up?

**Comment by david-melendez** [comment]
Here is an example for the FSCL:

```
RenderMultiPointSymbol(
    "ID",
    "FIRE SUPPORT COORDINATION LINE (FSCL)",
    "FIRE SUPPORT COORDINATION LINE (FSCL)",
    "GFFPLCF---****X",
    "-86.5540161132813,30.5465259552002 -86.5430755615234,30.5463237762451",
    "clampToGround",
    50000,
    "",
    "",
    0,
    1);
```

**Comment by michael-spinelli** [comment]
Sorry it took so long for a response.
If you're zoomed in and can set a bounding box for the visible map area, we recommend you do so:

bbox = "30.5261,86.5202,30.56897,86.58288";
RenderMultiPointSymbol(
    "ID",
    "FIRE SUPPORT COORDINATION LINE (FSCL)",
    "FIRE SUPPORT COORDINATION LINE (FSCL)",
    "GFFPLCF---****X",
    "-86.5540161132813,30.5465259552002 -86.5430755615234,30.5463237762451",
    "clampToGround",
    50000,
    bbox,
    "",
    0,
    1);

**Comment by david-melendez** [comment]
This suggestion did not work.
