### ISSUE TITLE
IED Symbol Does Not Match Standard

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#76]
The IED Explosion Symbol does not match the symbol as presented in the USAS supplements to the MIL-STD 2525.  The pictures below show the pages for the USAS documents for both the B and C standard as well as the symbols generated by our tool using the Java Renderer.

![trac_204_b](https://user-images.githubusercontent.com/22623059/30437353-00f6d450-9934-11e7-96a1-7d9eedbb34fb.png)

![trac_204_c](https://user-images.githubusercontent.com/22623059/30437360-0403ccf2-9934-11e7-81df-708c9898e98d.png)

**Comment by michael-spinelli** [comment]
Check that you're sending the correct symbol code to the renderer.
It looks like you're sending "S*G*EXI--------" (IED) instead of "O*V*EI---------" (IED explosion).
In my tester I'm getting the correct output.

**Comment by david-melendez** [comment]
You are correct.  Thanks!
