### ISSUE TITLE
Air Corridor Width Not Labeled Correctly

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#77]
According to the MIL-STD-2525C, the Width value for the Air Corridor is expressed in meters.   In the example in the standard, the text generated has an "m" at the end to indicate meters.  However, the renderer does not generate the "m".  See picture below.

![trac_203](https://user-images.githubusercontent.com/22623059/30439229-c9dd9256-9938-11e7-86ee-18ba5ce11f64.png)

Our customer would like the "m" to be generated so that it can be displayed on our map.

**Comment by michael-spinelli** [comment]
fixed. will be available in next release v0.1.28
