### ISSUE TITLE
contribute example (not really an issue)

### ISSUE THREAD

**Issue by jimwinston** [missioncommand/old-mil-sym-java#8]
I fiddled with you multipPoints.html and added a form to allow a user to enter most of the parameters like 2525 code, bounding box, and control points. It's not pretty, but it works. Would you like it? I couldn't figure out a way to contact the developers other than this.

**Comment by michael-spinelli** [comment]
Sure.  That would be a useful thing to have available.  Email it to: michael.spinelli@us.army.mil
rename it from html to txt.  Our mail filter is pretty aggressive and I'm not sure if an html file would make it through.  Or you can join this google group and post it:
https://groups.google.com/forum/#!forum/mission-command-milstd-renderer

**Comment by michael-spinelli** [comment]
Thanks, integrated, updated and posted as multPoints2.html
