### ISSUE TITLE
getBasicSymbolID returns incorrect value

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#80]
The following code returns an incorrect value:

```
// Expect "E*O*DK----*****", but I get "E*O*DK----H****"
String id = SymbolUtilities.getBasicSymbolID("EFOPDK---------");
```

**Comment by michael-spinelli** [comment]
checked in a fix. available in next release

**Comment by david-melendez** [comment]
I have tried this fix and it does not appear to be working correctly.   The fix that was entered assumes the the PRISON symbol is an installation and should have an 'H' in the eleventh position.  However, according to the standard, the "E*O*DK----*****" symbol is not an installation.

I believe I have tracked down the problem to the following code in the getBasicSymbolID method:

```
strRetSymbolID = strRetSymbolID + "*****";
UnitDefTable udt = UnitDefTable.getInstance();
String temp = strRetSymbolID;
for(int i = 0; i < 2; i++)
{
	if(udt.HasUnitDef(temp,i)==true)
	{
		return temp;
	}
	else
	{
		temp = temp.substring(0,10) + "H****";
****>>     if(udt.HasUnitDef(temp,i)==true)
		{
			return temp;
		}
		else
		{
			temp = temp.substring(0,10) + "MO***";
			if(udt.HasUnitDef(temp,i)==true)
			{
				return temp;
			}
		}
	}
	temp = temp.substring(0,10) + "*****";
}

```
Notice the line that checks for `udt.HasUnitDef(temp,i) == true.`  This method checks the UnitConstanctsC.xml file that has an entry for the PRISON symbol with the symbolID = `"E*O*DK----H*****"`.  I believe this entry is wrong as the standard does not have the H specified.

**Comment by michael-spinelli** [comment]
2525C:
![image](https://user-images.githubusercontent.com/5972575/31966705-85a46f68-b8d9-11e7-8fc1-1e5f27a7784e.png)
USAS also calls it an EMS installation.

**Comment by david-melendez** [comment]
OK, I see the problem.  Table G-III for EMS symbols does not show the H modifier on the symbol, but the G-VI table and the USAS document does have the H modifier.    I have tested the latest change and everything seems to be working.
