### ISSUE TITLE
Hostile battle position symbol has an excessive amount of ENY labels

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/old-mil-sym-java#81]
The behavior is expected and it is by design. I enhanced the reindeer by adding an option to display ENY labels in all segments, or to only display the label 2 times, one in the north and the other one in the south of the hostile graphics that display ENY.

**Comment by michael-spinelli** [comment]
v0.1.29
Option in RendererSettings
RendererSettings.getTwoLabelOnly(bool)
