### ISSUE TITLE
.war Renderer fails on 2525C Mine Contacts

### ISSUE THREAD

**Issue by JMBennett** [missioncommand/old-mil-sym-java#9]
Using the .war renderer, per MIL-STD-2525C (http://www.dtic.mil/doctrine//doctrine/other/ms_2525c.pdf [pg.288]) mine contacts have a bordering frame to denote affiliation.

Requesting the following image results in affiliation being lost.

renderer/image/SUUPWMD---*****?symStd="2525C"

**Comment by michael-spinelli** [comment]
I see it, there was a bug with checking against the MilStd for subsurface symbols. Fix checked in.  I'll make an updated release sometime today.  Thanks.
