### ISSUE TITLE
Screen, Guard, Cover rotation line issue

### ISSUE THREAD

**Issue by jtharp** [missioncommand/old-mil-sym-java#91]
We have noticed when using Screen/Guard/Cover the graphic looks good when in a straight horizontal line.

However hen rotated the graphic does not line up in the center. Depending on what is in the center of the graphic it can look odd and not obvious which symbol it is attached to.

See screenshots showing horizontal then rotated version of the guard graphic.

![guard-normal](https://user-images.githubusercontent.com/7952457/41306279-344fe67a-6e3b-11e8-9dfa-bc821cbdac94.PNG)

![guard-issue](https://user-images.githubusercontent.com/7952457/41306281-38d904d8-6e3b-11e8-95fa-6beff98e9e1c.PNG)

**Comment by jtharp** [comment]
Any thoughts on this issue? The customer I work with deems it a priority issue as it can add confusion to the planning and understanding of the battlefield.

**Comment by michael-spinelli** [comment]
Are your requirements for 2525B or 2525C?
If C, I'd recommend using the 4 point version of the symbol.
if B, I'd recommend using the 4 point version and extrapolating 4 points based on the 3 provided for the B version of the symbol.

Unfortunately, no one is tasked to work on the renderer currently.  

Reviewing and approving pull requests is all I've had time for lately.

If your government customer would like to throw some money at the problem, I can try to point them in the right direction.  Or if you have people that would like to make a pull request with a fix, that's cool too.

**Comment by jtharp** [comment]
Ok that is good information. We are still mainly 2525B at this point.
I will inquire about resources. If there is something there I will get with you offline.

I am familiar with the old C# MCS renderer but I have not had time to dedicate to this issue.
