### ISSUE TITLE
Function ID not working in JavaRenderer

### ISSUE THREAD

**Issue by itlmos** [missioncommand/old-mil-sym-java#93]
When specifying a Function ID of a symbol for the JavaRenderer, it does not render the image any differently.

Consider the following Java code:

String code = "SFGPIMFPW-H-";
        BufferedImage image = JavaRenderer.getInstance().RenderMilStdSymbolAsIcon(code, 130, Boolean.TRUE);
        imageView.setImage(SwingFXUtils.toFXImage(image, null));
       
This renders the image correctly, except that the Function ID modifier isn't applied.

Please advise?

**Comment by michael-spinelli** [comment]
I'll have to check that.

**Comment by michael-spinelli** [comment]
So I did this:
BufferedImage blah = JavaRenderer.getInstance().RenderMilStdSymbolAsIcon("SFGPIMFPW-H----", 130, Boolean.TRUE);
                    File outFileBlah = new File("C:/temp/blah.png");
                    try
                    {
                        ImageIO.write(blah, "png",outFileBlah);
                    }
                    catch(IOException ioe)
                    {
                        ErrorLogger.LogMessage(ioe.getMessage());
                    }

and got this:

![blah](https://user-images.githubusercontent.com/5972575/44170792-6e479380-a0a6-11e8-88ef-6e8d5d3ee6cc.png)

**Comment by michael-spinelli** [comment]
Can you post an image of what you're getting and why you believe it is incorrect?
