### ISSUE TITLE
Version 0.1.37 No Longer Renders SigInt Symbols Properly

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#99]
Below is a screen shot of some sigint symbols that are being rendered incorrectly.  Notice that the neutral and unknown symbols are correct, but the friendly and hostile are not.  This happens in 0.1.37.

![image](https://user-images.githubusercontent.com/22623059/67971307-8f789f00-fbda-11e9-9457-e2ece4d39fd4.png)

If I switch to 0.1.36, this is what I get.

![image](https://user-images.githubusercontent.com/22623059/67971445-c77fe200-fbda-11e9-86d6-8277b8ce3a67.png)

As you can see, all the symbols are generated correctly.

**Comment by michael-spinelli** [comment]
fixed in 0.1.38
